'use client';

import React from 'react';
import Link from 'next/link';
import { ArrowLeft, Shield } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 p-6 md:p-12 max-w-4xl mx-auto font-sans">
      <Link href="/" className="inline-flex items-center gap-2 text-xs font-semibold text-purple-400 hover:text-purple-300 mb-8 transition-colors">
        <ArrowLeft size={14} /> Back to FxZone
      </Link>

      <div className="flex items-center gap-3 mb-6 border-b border-zinc-800 pb-4">
        <Shield size={28} className="text-purple-400" />
        <h1 className="text-3xl font-black text-white">Terms of Service</h1>
      </div>

      <div className="space-y-6 text-sm text-zinc-300 leading-relaxed font-normal">
        <p className="text-xs text-zinc-400">Last updated: August 2026</p>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white">1. Acceptance of Terms</h2>
          <p>By accessing or using the FxZone platform ("Service"), you agree to be bound by these Terms of Service. FxZone provides financial market intelligence, AI technical analysis tools, and workspace utilities.</p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white">2. Informational & Non-Financial Advice Disclaimer</h2>
          <p>All content, market data, technical indicators, and Gemini AI sentiment analysis generated by FxZone are provided strictly for educational and analytical purposes. FxZone is not a registered broker-dealer, financial advisor, or asset manager.</p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white">3. User Accounts & Security</h2>
          <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities occurring under your account.</p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white">4. Market Data & Third-Party APIs</h2>
          <p>FxZone aggregates market data from external third-party providers. While we aim for low-latency delivery, FxZone does not guarantee uninterrupted or error-free feed streaming.</p>
        </section>
      </div>
    </div>
  );
}
