-- Long social videos upload directly from the authenticated browser using a
-- single-use URL issued by app/api/social/posts/upload-url. The function body
-- never passes through Vercel, whose request-size cap is lower than the
-- product video limit. Storage still enforces this bucket-level limit.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'post-media',
  'post-media',
  true,
  104857600,
  ARRAY[
    'image/jpeg', 'image/png', 'image/gif', 'image/webp',
    'video/mp4', 'video/quicktime', 'video/webm', 'video/x-matroska',
    'audio/webm', 'audio/mp3', 'audio/mpeg', 'audio/wav', 'audio/ogg',
    'application/pdf'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Browser clients receive only a short-lived upload token generated by the
-- authenticated Next.js route. They do not need a general INSERT policy that
-- would permit writing arbitrary post-media objects with the public key.
DROP POLICY IF EXISTS "Post media user upload" ON storage.objects;
